### ISSUE TITLE
WRONG Pin Assignment

### ISSUE THREAD

**Issue by HongjieMaTJU** [RobTillaart/SHT85#6]
// TOPVIEW
    //            +-------+
    // +-----\    | SDA 4 -----
    // | /-+  ----+ VCC 3 -----
    // | +-+  ----+ GND 2 -----
    // +-----/    | SCL 1 -----
    //            +-------+

The second pin should be VCC and the third pin should be GND.

Misled and caused an expensive sensor to be damaged. :-(

**Comment by RobTillaart** [comment]
I'm sorry to hear, I will verify again the datasheet today and update documentation if needed.

**Comment by RobTillaart** [comment]
From preliminary datasheet version 0.9 - September 2018 - page 8

![image](https://user-images.githubusercontent.com/462844/138034939-60adf6fc-b0e4-48ca-83bf-7512162bde7e.png)

----

Checked SHT85_demo.ino =>right picture => OK
Checked SHT85_demo_plotter.ino =>right picture => OK
Checked SHT85_I2C_speed.ino =>right picture => OK
Checked the SHT85.h => wrong picture => **FIX**
Checked the SHT85.cpp => no picture => OK
Checked the readme.md => wrong picture => **FIX**
Checked unit_test_001.cpp => no picture => OK
Checked keywords.txt  => no picture => OK
Checked library.json => no picture => OK
Checked library.properties => no picture => OK
Checked .arduino-ci.yml  => no picture => OK
Checked LICENSE => no picture => OK

Will create a PR with fixed images and release a 0.2.1 version a.s.a.p.

**Comment by RobTillaart** [comment]
Created release 0.3.0 with pictures fixed.

**Comment by RobTillaart** [comment]
Released.

**Comment by HongjieMaTJU** [comment]
That's great, Thank you.
